In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("weather_data.csv")
df.head()

         day  temp condition
0     Monday    12     Sunny
1    Tuesday    14      Rain
2  Wednesday    15      Rain
3   Thursday    14    Cloudy
4     Friday    21     Sunny

In [5]:
df.dtypes

day          object
temp          int64
condition    object
dtype: object

In [6]:
df_dict = df.to_dict()
df_dict

{'day': {0: 'Monday',
  1: 'Tuesday',
  2: 'Wednesday',
  3: 'Thursday',
  4: 'Friday',
  5: 'Saturday',
  6: 'Sunday'},
 'temp': {0: 12, 1: 14, 2: 15, 3: 14, 4: 21, 5: 22, 6: 24},
 'condition': {0: 'Sunny',
  1: 'Rain',
  2: 'Rain',
  3: 'Cloudy',
  4: 'Sunny',
  5: 'Sunny',
  6: 'Sunny'}}

In [9]:
df_dict = df["temp"].to_list()
df_dict

[12, 14, 15, 14, 21, 22, 24]

In [12]:
df_temp_avg = df["temp"].mean() 
print(df_temp_avg)

17.428571428571427

In [13]:
df_temp_avg = sum(df_dict) / len(df_dict)
df_temp_avg

17.428571428571427

In [14]:
print(df["temp"].max())

24

In [16]:
print(df["condition"])

0     Sunny
1      Rain
2      Rain
3    Cloudy
4     Sunny
5     Sunny
6     Sunny
Name: condition, dtype: object

In [17]:
df.condition

0     Sunny
1      Rain
2      Rain
3    Cloudy
4     Sunny
5     Sunny
6     Sunny
Name: condition, dtype: object

In [19]:
df[df.day == "Monday"]

      day  temp condition
0  Monday    12     Sunny

In [22]:
df[df.temp == df.temp.max()]

      day  temp condition
6  Sunday    24     Sunny

In [23]:
squir = pd.read_csv("2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv")
squir.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086)
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,True,me,POINT (-73.9570437717691 40.794850940803904)
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,NaN,...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9768311751004 40.76671780725581)
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Juvenile,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9757249834141 40.7697032606755)
4,-73.959313,40.797533,39B-AM-1018-01,39B,AM,10182018,1,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,NaN,POINT (-73.9593126695714 40.797533370163)

In [26]:
squir_grey = len(squir[squir["Primary Fur Color"] == "Gray"])
squir_red = len(squir[squir["Primary Fur Color"] == "Cinnamon"])
squir_black = len(squir[squir["Primary Fur Color"] == "Black"])
print(squir_grey)
print(squir_grey)
print(squir_black)

2473
2473
103

In [27]:
data_dict = {
    "Fur Color": ["Gray","Cinnamon", "Black"],
    "Count: ": [squir_grey,squir_red,squir_black]
}

In [31]:
new_squir = pd.DataFrame(data_dict)
new_squir
df.to_csv("new_squir.csv")