# The GroupBy Object

In [1]:
import pandas as pd

## The Fortune 1000 Dataset
- The **Fortune 1000** is a listing of the 1000 largest American companies as ranked by Fortune magazine.
- The **DataFrame** includes the company's name, sector, industry, and revenues, profits, and employees.

In [3]:
fortune = pd.read_csv("fortune1000.csv")
fortune.head()

,Rank,Company,Sector,Industry,Revenue,Profits,Employees
0,1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
1,2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
2,3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
3,4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
4,5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

## The groupby Method
- **Grouping** is a way to organize/categorize/group the data based on a column's values.
- The `groupby` method returns a **DataFrameGroupBy** object. It resembles a group/collection of **DataFrames** in a dictionary-like structure.
- The **DataFrameGroupBy** object can perform aggregate operations on *each* group within it.

In [19]:
# Sum of revenues for each Sectors

sectors = fortune.groupby("Sector")
sectors

In [22]:
len(sectors)

21

In [23]:
sectors.size()

Sector
Aerospace & Defense              20
Apparel                          15
Business Services                51
Chemicals                        30
Energy                          122
Engineering & Construction       26
Financials                      139
Food and Drug Stores             15
Food, Beverages & Tobacco        43
Health Care                      75
Hotels, Resturants & Leisure     25
Household Products               28
Industrials                      46
Materials                        43
Media                            25
Motor Vehicles & Parts           24
Retailing                        80
Technology                      102
Telecommunications               15
Transportation                   36
Wholesalers                      40
dtype: int64

In [24]:
sectors.first()

,Rank,Company,Industry,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,24,Boeing,Aerospace and Defense,96114,5176,161400
Apparel,91,Nike,Apparel,30601,3273,62600
Business Services,144,ManpowerGroup,Temporary Help,19330,419,27000
Chemicals,56,Dow Chemical,Chemicals,48778,7685,49495
Energy,2,Exxon Mobil,Petroleum Refining,246204,16150,75600
Engineering & Construction,155,Fluor,"Engineering, Construction",18114,413,38758
Financials,4,Berkshire Hathaway,Insurance: Property and Casualty (Stock),210821,24083,331000
Food and Drug Stores,7,CVS Health,Food and Drug Stores,153290,5237,199000
"Food, Beverages & Tobacco",41,Archer Daniels Midland,Food Production,67702,1849,32300
Health Care,5,McKesson,Wholesalers: Health Care,181241,1476,70400
"Hotels, Resturants & Leisure",109,McDonald’s,Food Services,25413,4529,420000
Household Products,34,Procter & Gamble,Household and Personal Products,78756,7036,110000
Industrials,11,General Electric,Industrial Machinery,140389,-6126,333000
Materials,126,Alcoa,Metals,22534,-322,60000
Media,53,Disney,Entertainment,52465,8382,185000
Motor Vehicles & Parts,8,General Motors,Motor Vehicles and Parts,152356,9687,215000
Retailing,1,Walmart,General Merchandisers,482130,14694,2300000
Technology,3,Apple,"Computers, Office Equipment",233715,53394,110000
Telecommunications,10,AT&T,Telecommunications,146801,13345,281450
Transportation,48,UPS,"Mail, Package, and Freight Delivery",58363,4844,341240
Wholesalers,57,Sysco,Wholesalers: Food and Grocery,48681,687,51700

## Retrieve a Group with the get_group Method
- The `get_group` method on the **DataFrameGroupBy** object retrieves a nested **DataFrame** belonging to a specific group/category.

In [28]:
fortune = pd.read_csv("fortune1000.csv",index_col="Rank")
sectors = fortune.groupby("Sector")

fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [31]:
sectors.get_group("Energy")
sectors.get_group("Technology")

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
18,Amazon.com,Technology,Internet Services and Retailing,107006,596,230800
20,HP,Technology,"Computers, Office Equipment",103355,4554,287000
25,Microsoft,Technology,Computer Software,93580,12193,118000
31,IBM,Technology,Information Technology Services,82461,13190,411798
...,...,...,...,...,...,...
970,Rackspace Hosting,Technology,Internet Services and Retailing,2001,126,6189
971,VeriFone Systems,Technology,"Computers, Office Equipment",2001,79,5400
975,Super Micro Computer,Technology,"Computers, Office Equipment",1991,102,2285
984,Nuance Communications,Technology,Computer Software,1931,-115,13500
990,F5 Networks,Technology,Network and Other Communications Equipment,1920,365,4178

## Methods on the GroupBy Object
- Use square brackets on the **DataFrameGroupBy** object to "extract" a column from the original **DataFrame**.
- The resulting **SeriesGroupBy** object will have aggregation methods available on it.
- Pandas will perform the calculation on *every* group within the collection.
- For example, the `sum` method will sum together the **Revenues** for every row by group/category.

In [32]:
fortune = pd.read_csv("fortune1000.csv",index_col="Rank")
sectors = fortune.groupby("Sector")

fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [35]:
sectors["Revenue"].sum()
sectors["Employees"].sum()

Sector
Aerospace & Defense              968057
Apparel                          346397
Business Services               1361050
Chemicals                        463651
Energy                          1188927
Engineering & Construction       406708
Financials                      3359948
Food and Drug Stores            1395398
Food, Beverages & Tobacco       1211632
Health Care                     2678289
Hotels, Resturants & Leisure    2484245
Household Products               646038
Industrials                     1545229
Materials                        638123
Media                            550314
Motor Vehicles & Parts          1082560
Retailing                       6227629
Technology                      3578949
Telecommunications               832468
Transportation                  1536793
Wholesalers                      525597
Name: Employees, dtype: int64

In [38]:
sectors[["Revenue","Profits"]].sum()

                              Revenue  Profits
Sector
Aerospace & Defense            357940    28742
Apparel                         95968     8236
Business Services              272195    28227
Chemicals                      243897    22628
Energy                        1517809   -73447
Engineering & Construction     153983     5304
Financials                    2217159   260209
Food and Drug Stores           483769    16759
Food, Beverages & Tobacco      555967    51417
Health Care                   1614707   106114
Hotels, Resturants & Leisure   169546    20697
Household Products             234737    14428
Industrials                    497581    20764
Materials                      259145     4428
Media                          220764    24347
Motor Vehicles & Parts         482540    25898
Retailing                     1465076    47830
Technology                    1377600   180473
Telecommunications             461834    48637
Transportation                 408508    44169
Wholesalers                    444800     8233

## Grouping by Multiple Columns
- Pass a list of columns to the **groupby** method to group by pairings of values across columns.
- Target a column to retrieve the **SeriesGroupBy** object, then perform an aggregation with a method.
- Pandas will return a **MultiIndex** **Series** where the levels will be the original groups.

In [46]:
fortune = pd.read_csv("fortune1000.csv",index_col="Rank")
sectors = fortune.groupby(["Sector","Industry"])

fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [47]:
sectors["Revenue"].sum()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            357940
Apparel              Apparel                                           95968
Business Services    Advertising, marketing                            22748
                     Diversified Outsourcing Services                  64829
                     Education                                          7485
                                                                       ...
Transportation       Trucking, Truck Leasing                           35950
Wholesalers          Miscellaneous                                      8982
                     Wholesalers: Diversified                         176138
                     Wholesalers: Electronics and Office Equipment    147906
                     Wholesalers: Food and Grocery                    111774
Name: Revenue, Length: 79, dtype: int64

In [48]:
sectors["Profits"].mean()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            1437.100000
Apparel              Apparel                                           549.066667
Business Services    Advertising, marketing                            774.500000
                     Diversified Outsourcing Services                  307.500000
                     Education                                          23.000000
                                                                         ...
Transportation       Trucking, Truck Leasing                           212.222222
Wholesalers          Miscellaneous                                      17.000000
                     Wholesalers: Diversified                          207.720000
                     Wholesalers: Electronics and Office Equipment     232.125000
                     Wholesalers: Food and Grocery                     194.333333
Name: Profits, Length: 79, dtype: float64

## The agg Method
- The `agg` method applies different aggregation methods on different columns.
- Invoke the `agg` method directly on the **DataFrameGroupBy** object.
- Pass the method a dictionary where the keys are the columns and the values are the aggregation operations.

In [51]:
fortune = pd.read_csv("fortune1000.csv",index_col="Rank")
sectors = fortune.groupby("Sector")

fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [53]:
sectors.agg({"Revenue":"sum","Profits":"max"})

                              Revenue  Profits
Sector
Aerospace & Defense            357940     7608
Apparel                         95968     3273
Business Services              272195     6328
Chemicals                      243897     7685
Energy                        1517809    16150
Engineering & Construction     153983      803
Financials                    2217159    24442
Food and Drug Stores           483769     5237
Food, Beverages & Tobacco      555967     7351
Health Care                   1614707    18108
Hotels, Resturants & Leisure   169546     5920
Household Products             234737     7036
Industrials                    497581     4833
Materials                      259145      991
Media                          220764     8382
Motor Vehicles & Parts         482540     9687
Retailing                     1465076    14694
Technology                    1377600    53394
Telecommunications             461834    17879
Transportation                 408508     7610
Wholesalers                    444800     1472

## Iterating through Groups 
- The **DataFrameGroupBy** object supports the `apply` method (just like a **Series** and a **DataFrame** do).
- The `apply` method invokes a function on every nested **DataFrame** in the **DataFrameGroupBy** object.
- It captures the return values of the functions and collects them in a new **DataFrame** (the return value).

In [54]:
fortune = pd.read_csv("fortune1000.csv",index_col="Rank")
sectors = fortune.groupby("Sector")

fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [55]:
# Find the two companies in each sector with the most employees

fortune.nlargest(2,"Employees")

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
218,Yum Brands,"Hotels, Resturants & Leisure",Food Services,13105,1293,505000

In [56]:
def top_two_companies_by_employees_count(sector):
    return sector.nlargest(2,"Employees")

sectors.apply(top_two_companies_by_employees_count)

                                                    Company  \
Sector                       Rank
Aerospace & Defense          45         United Technologies
                             24                      Boeing
Apparel                      448                Hanesbrands
                             231                         VF
Business Services            199                    Aramark
                             744                  Convergys
Chemicals                    101                     DuPont
                             56                Dow Chemical
Energy                       2                  Exxon Mobil
                             117                Halliburton
Engineering & Construction   156                      AECOM
                             235   Jacobs Engineering Group
Financials                   4           Berkshire Hathaway
                             27                 Wells Fargo
Food and Drug Stores         17                      Kroger
                             19    Walgreens Boots Alliance
Food, Beverages & Tobacco    44                     PepsiCo
                             62                   Coca-Cola
Health Care                  63                HCA Holdings
                             6           UnitedHealth Group
Hotels, Resturants & Leisure 218                 Yum Brands
                             109                 McDonald’s
Household Products           34            Procter & Gamble
                             256     Stanley Black & Decker
Industrials                  11            General Electric
                             75     Honeywell International
Materials                    126                      Alcoa
                             127        International Paper
Media                        53                      Disney
                             255      R.R. Donnelley & Sons
Motor Vehicles & Parts       8               General Motors
                             9                   Ford Motor
Retailing                    1                      Walmart
                             28                  Home Depot
Technology                   31                         IBM
                             20                          HP
Telecommunications           10                        AT&T
                             13                     Verizon
Transportation               48                         UPS
                             58                       FedEx
Wholesalers                  212                     Synnex
                             57                       Sysco

                                                                        Industry  \
Sector                       Rank
Aerospace & Defense          45                            Aerospace and Defense
                             24                            Aerospace and Defense
Apparel                      448                                         Apparel
                             231                                         Apparel
Business Services            199                Diversified Outsourcing Services
                             744                Diversified Outsourcing Services
Chemicals                    101                                       Chemicals
                             56                                        Chemicals
Energy                       2                                Petroleum Refining
                             117                 Oil and Gas Equipment, Services
Engineering & Construction   156                       Engineering, Construction
                             235                       Engineering, Construction
Financials                   4          Insurance: Property and Casualty (Stock)
                             27                                 Commercial Banks
Food and Drug Stores         17                             Food and Drug Stores
                             19                             Food and Drug Stores
Food, Beverages & Tobacco    44                           Food Consumer Products
                             62                                        Beverages
Health Care                  63                  Health Care: Medical Facilities
                             6           Health Care: Insurance and Managed Care
Hotels, Resturants & Leisure 218                                   Food Services
                             109                                   Food Services
Household Products           34                  Household and Personal Products
                             256                     Home Equipment, Furnishings
Industrials                  11                             Industrial Machinery
                             75                   Electronics, Electrical Equip.
Materials                    126                                          Metals
                             127                           Packaging, Containers
Media                        53                                    Entertainment
                             255                            Publishing, Printing
Motor Vehicles & Parts       8                          Motor Vehicles and Parts
                             9                          Motor Vehicles and Parts
Retailing                    1                             General Merchandisers
                             28                       Specialty Retailers: Other
Technology                   31                  Information Technology Services
                             20                      Computers, Office Equipment
Telecommunications           10                               Telecommunications
                             13                               Telecommunications
Transportation               48              Mail, Package, and Freight Delivery
                             58              Mail, Package, and Freight Delivery
Wholesalers                  212   Wholesalers: Electronics and Office Equipment
                             57                    Wholesalers: Food and Grocery

                                   Revenue  Profits  Employees
Sector                       Rank
Aerospace & Defense          45      61047     7608     197200
                             24      96114     5176     161400
Apparel                      448      5732      429      65300
                             231     12377     1232      64000
Business Services            199     14329      236     216500
                             744      2951      169     130000
Chemicals                    101     27940     1953      52000
                             56      48778     7685      49495
Energy                       2      246204    16150      75600
                             117     23633     -671      65000
Engineering & Construction   156     17990     -155      92000
                             235     12115      303      56950
Financials                   4      210821    24083     331000
                             27      90033    22894     264700
Food and Drug Stores         17     109830     2039     431000
                             19     103444     4220     302500
Food, Beverages & Tobacco    44      63056     5452     263000
                             62      44294     7351     123200
Health Care                  63      43591     2129     203500
                             6      157107     5813     200000
Hotels, Resturants & Leisure 218     13105     1293     505000
                             109     25413     4529     420000
Household Products           34      78756     7036     110000
                             256     11211      884      51250
Industrials                  11     140389    -6126     333000
                             75      38581     4768     129000
Materials                    126     22534     -322      60000
                             127     22365      938      56000
Media                        53      52465     8382     185000
                             255     11257      151      68400
Motor Vehicles & Parts       8      152356     9687     215000
                             9      149558     7373     199000
Retailing                    1      482130    14694    2300000
                             28      88519     7009     385000
Technology                   31      82461    13190     411798
                             20     103355     4554     287000
Telecommunications           10     146801    13345     281450
                             13     131620    17879     177700
Transportation               48      58363     4844     341240
                             58      47453     1050     323035
Wholesalers                  212     13338      209      78500
                             57      48681      687      51700